### ISSUE TITLE
How install PyQt5 

### ISSUE THREAD

**Issue by aesolkim** [fox-it/mkYARA#1]
i want install PyQt5 in Window x86
ida python just use python 2.x  but PyQt5 supposed in python 3.x.
i already try everything. :(

**Comment by jellever** [comment]
Hi! Sorry for the slow response! I'm not entirely sure what the issue is you are running into. You don't need to install PyQt5, as this package is already installed within the IDA python environment.

**Comment by aesolkim** [comment]
Hi, I installed that in IDA 7.0, it run pretty well. :) Thanks to your
response!

2019년 5월 10일 (금) 오후 9:00, Jelle Vergeer <notifications@github.com>님이 작성:
